sudo: required
services:
  - docker

before_install:
  - docker build -t gapeevdi/test-client-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  gapeevdi/test-client-app npm run test

after_success:
  - docker build -t gapeevdi/multi-client-app ./client
  - docker build -t gapeevdi/multi-nginx ./nginx
  - docker build -t gapeevdi/multi-server ./server
  - docker build -t gapeevdi/multi-service ./service
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gapeevdi/multi-client-app
  - docker push gapeevdi/multi-nginx
  - docker push gapeevdi/multi-server
  - docker push gapeevdi/multi-service

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: MultiDocker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-140254542102
  bucker_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY